packageExtensions:
  "@yarnpkg/cli@*":
    dependencies:
      "@yarnpkg/cli": "*"
  "@yarnpkg/core@*":
    dependencies:
      "@types/lodash": "*"
  "@yarnpkg/plugin-npm@*":
    dependencies:
      "@yarnpkg/core": "*"
      "@yarnpkg/plugin-pack": "*"
  "@yarnpkg/plugin-pack@*":
    dependencies:
      "@yarnpkg/cli": "*"
  "@yarnpkg/plugin-patch@*":
    dependencies:
      "@yarnpkg/cli": "*"
      "@yarnpkg/core": "*"
  webpack@*:
    dependencies:
      terser-webpack-plugin: "*"
