import { rlocation } from "@rules-javascript/nodejs-runfiles";
import {
  InstallEntry,
  InstallManifest,
  installManifestFormat,
} from "@rules-javascript/pkg-install-manifest";
import { JsonFormat } from "@rules-javascript/util-json";
import { ArgumentParser } from "argparse";
import { createHash } from "node:crypto";
import {
  chmod,
  copyFile,
  mkdir,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { join } from "node:path";

(async () => {
  const parser = new ArgumentParser();
  parser.add_argument("--package-manager-state-file");
  parser.add_argument("manifest");
  parser.add_argument("output");
  const args = parser.parse_args();

  const manifestContent = await readFile(args.manifest, "utf8");
  const manifest = JsonFormat.parse(
    installManifestFormat(false),
    manifestContent,
  );

  const existingPath = join(args.output, ".install-manifest.json");
  const packageManagerStatePath = args.package_manager_state_file
    ? join(args.output, args.package_manager_state_file)
    : undefined;
  let existing: InstallManifest | undefined;
  try {
    const existingContent = await readFile(existingPath, "utf8");
    if (manifestContent === existingContent) {
      await writePackageManagerState(packageManagerStatePath, manifestContent);
      return;
    }
    existing = JsonFormat.parse(installManifestFormat(false), existingContent);
    await rm(existingPath); // don't allow partial progress
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      await rm(args.output, { force: true, recursive: true });
    } else {
      throw error;
    }
  }

  await install(manifest, existing, args.output);
  await writeFile(existingPath, manifestContent);
  await writePackageManagerState(packageManagerStatePath, manifestContent);
})().catch((error) => {
  console.error(error);
  process.exit(1);
});

async function writePackageManagerState(
  path: string | undefined,
  manifestContent: string,
) {
  if (!path) {
    return;
  }
  const manifestSha256 = createHash("sha256")
    .update(manifestContent)
    .digest("hex");
  const content = [
    "# Warning: This file is automatically generated. Removing it is fine, but will",
    "# cause your node_modules installation to become invalidated.",
    "",
    "__metadata:",
    "  version: 1",
    "  nmMode: classic",
    `  rulesJavascriptInstallManifestSha256: ${manifestSha256}`,
    "",
  ].join("\n");
  try {
    if ((await readFile(path, "utf8")) === content) {
      return;
    }
  } catch (error) {
    if (
      !(error instanceof Error && "code" in error && error.code === "ENOENT")
    ) {
      throw error;
    }
  }
  await writeFile(path, content);
}

async function install(
  manifest: InstallEntry,
  existing: InstallEntry | undefined,
  path: string,
) {
  switch (manifest.type) {
    case InstallEntry.DIR: {
      if (existing && existing.type !== InstallEntry.DIR) {
        await rm(path, { recursive: existing.type !== InstallEntry.FILE });
        existing = undefined;
      }
      await (existing
        ? Promise.all(
            [...existing.entries.entries()].map(async ([name, entry]) => {
              if (!manifest.entries.has(name)) {
                const childPath = join(path, name);
                await rm(childPath, {
                  recursive: entry.type !== InstallEntry.FILE,
                });
              }
            }),
          )
        : mkdir(path));
      await Promise.all(
        [...manifest.entries.entries()].map(async ([name, entry]) => {
          const childPath = join(path, name);
          await install(
            entry,
            (existing as InstallEntry.Dir | undefined)?.entries.get(name),
            childPath,
          );
        }),
      );
      break;
    }
    case InstallEntry.FILE: {
      if (
        existing &&
        !(
          existing.type == InstallEntry.FILE &&
          manifest.digest.equals(existing.digest)
        )
      ) {
        await rm(path, { recursive: existing.type !== InstallEntry.FILE });
        existing = undefined;
      }
      if (!existing) {
        await copyFile(rlocation(manifest.src)!, path);
        await chmod(path, manifest.executable ? 0o755 : 0o644);
      }
      break;
    }
    case InstallEntry.SYMLINK: {
      if (
        existing &&
        !(
          existing.type === InstallEntry.SYMLINK &&
          existing.target === manifest.target
        )
      ) {
        await rm(path, { recursive: existing.type !== InstallEntry.FILE });
        existing = undefined;
      }
      if (!existing) {
        await symlink(manifest.target, path);
      }
      break;
    }
  }
}
