import { PackageTree } from "@rules-javascript/commonjs-package";
import { PortablePath } from "@yarnpkg/fslib";
import {
  DependencyTarget,
  LinkType,
  PackageStoreData,
  PhysicalPackageLocator,
  SerializedState,
  generateLoader,
  generatePrettyJson,
  getESMLoaderTemplate,
} from "@yarnpkg/pnp";
import { posix } from "node:path";

const ROOT_LOCATION = "./" as PortablePath;

/** Normalize a package path into a PnP package location (relative directory). */
function location(path: string): PortablePath {
  const normalized = posix.normalize(path).replace(/\/+$/, "");
  if (normalized === ".") {
    return ROOT_LOCATION;
  }
  // PnP wants a "./" prefix on subpaths; absolute and parent paths keep theirs.
  const relative = /^(\.\.(\/|$)|\/)/.test(normalized)
    ? normalized
    : `./${normalized}`;
  return `${relative}/` as PortablePath;
}

/**
 * Generate a Yarn Plug'n'Play file (`.pnp.cjs`) from a CommonJS package tree.
 *
 * Each package becomes a PnP package keyed by its path; its deps become package
 * dependencies. The roots become the dependency tree roots.
 */
export function pnpScript(tree: PackageTree, roots: string[]): string {
  if (!roots.length) {
    throw new Error("At least one root is required");
  }

  const nameByPath = new Map<string, string>();
  for (const [path, package_] of tree.packages) {
    nameByPath.set(path, package_.name);
  }

  const dependencyTreeRoots: PhysicalPackageLocator[] = [];
  for (const path of new Set(roots)) {
    const name = nameByPath.get(path);
    if (name === undefined) {
      throw new Error(`Root package "${path}" is not known`);
    }
    dependencyTreeRoots.push({ name, reference: path });
  }

  const target = (name: string, path: string): DependencyTarget => {
    const depName = nameByPath.get(path);
    if (depName === undefined) {
      throw new Error(`Package "${path}" (required as "${name}") is not known`);
    }
    return depName === name ? path : [depName, path];
  };

  const deps = (
    entries: Iterable<readonly [string, string]>,
  ): [string, DependencyTarget][] =>
    [...entries].map(([name, dep]): [string, DependencyTarget] => [
      name,
      target(name, dep),
    ]);

  // Packages are grouped under their name in the registry.
  const packageRegistry = new Map<string | null, PackageStoreData>();
  const store = (name: string | null): PackageStoreData => {
    let store = packageRegistry.get(name);
    if (store === undefined) {
      packageRegistry.set(name, (store = []));
    }
    return store;
  };

  for (const [path, package_] of tree.packages) {
    store(package_.name).push([
      path,
      {
        linkType: LinkType.HARD,
        packageLocation: location(path),
        // The leading self-reference lets the package require itself by name.
        packageDependencies: [
          [package_.name, path],
          ...deps(package_.deps),
        ],
      },
    ]);
  }

  // Use the top level for global dependencies. (Note: the top level is not a
  // real package, so it is discarded from location lookup.)
  store(null).push([
    null,
    {
      discardFromLookup: true,
      linkType: LinkType.HARD,
      packageLocation: ROOT_LOCATION,
      packageDependencies: deps(tree.globals),
    },
  ]);

  // Ideally, would use generateInlinedScript, but need to have more control
  // over the top-level package.
  const data: SerializedState = {
    __info: ["Generated by rules_javascript"],
    dependencyTreeRoots,
    enableTopLevelFallback: true,
    fallbackExclusionList: [],
    fallbackPool: [],
    ignorePatternData: null,
    packageRegistryData: [...packageRegistry],
    pnpZipBackend: "js",
  };

  return preserveSymlinks(
    generateLoader(undefined, generateInlinedSetup(data)),
  );
}

// PnP canonicalizes resolved modules with `realpathSync`, ignoring Node's
// `--preserve-symlinks`. Under Bazel runfiles that follows the runfiles symlink
// out of RUNFILES_DIR, so `findPackageLocator` no longer matches `__filename`.
// Skip the realpath and keep the symlinked path.
const REALPATH = "return opts.fakeFs.realpathSync(unqualifiedPath);";
const NO_REALPATH = "return unqualifiedPath;";

function preserveSymlinks(script: string): string {
  if (!script.includes(REALPATH)) {
    throw new Error(
      "Yarn PnP template changed: realpath resolution expression not found",
    );
  }
  return script.replace(REALPATH, NO_REALPATH);
}

/**
 * Generate the Yarn Plug'n'Play ESM loader (`.pnp.loader.mjs`).
 *
 * The loader is static: at runtime it finds the PnP API set up by the adjacent
 * `.pnp.cjs` (preloaded via `node --require`), so it must sit next to it.
 */
export function pnpLoader(): string {
  return getESMLoaderTemplate();
}

function generateStringLiteral(value: string) {
  return `'${value
    .replaceAll("\\", `\\\\`)
    .replaceAll("'", String.raw`\'`)
    .replaceAll("\n", `\\\n`)}'`;
}

function generateInlinedSetup(data: SerializedState) {
  return [
    `const RAW_RUNTIME_STATE =\n`,
    `${generateStringLiteral(generatePrettyJson(data))};\n\n`,
    `function $$SETUP_STATE(hydrateRuntimeState, basePath) {\n`,
    `  return hydrateRuntimeState(JSON.parse(RAW_RUNTIME_STATE), {basePath: basePath || __dirname});\n`,
    `}\n`,
  ].join(``);
}
